import type { TemplateConfig } from './types';

export const announcementTemplate: TemplateConfig = {
  id: 'announcement',
  name: 'Announcement',
  description: 'Centered, balanced layout for announcements and launches. Clean and authoritative.',
  safeArea: {
    square: { top: 120, right: 100, bottom: 110, left: 100 },
    story: { top: 320, right: 80, bottom: 220, left: 80 },
    landscape: { top: 100, right: 160, bottom: 110, left: 160 },
  },
  layout: {
    square: { justifyContent: 'center', gap: 20 },
    story: { justifyContent: 'center', gap: 28 },
    landscape: { justifyContent: 'center', gap: 18 },
  },
  zones: {
    kicker: {
      id: 'kicker',
      role: 'kicker',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 24, story: 26, landscape: 22 },
        fontWeight: 600,
        lineHeight: 1.3,
        letterSpacing: 3,
        textTransform: 'uppercase',
      },
      maxLines: 1,
      marginTop: 0,
      marginBottom: 10,
      opacity: 1,
    },
    headline: {
      id: 'headline',
      role: 'headline',
      typography: {
        fontFamily: 'headline',
        fontSize: { square: 72, story: 78, landscape: 64 },
        fontWeight: 700,
        lineHeight: 1.06,
        letterSpacing: -1.5,
        textTransform: 'none',
      },
      maxLines: 4,
      marginTop: 0,
      marginBottom: 8,
      opacity: 1,
    },
    subtitle: {
      id: 'subtitle',
      role: 'subtitle',
      typography: {
        fontFamily: 'headline',
        fontSize: { square: 34, story: 38, landscape: 32 },
        fontWeight: 500,
        lineHeight: 1.25,
        letterSpacing: -0.5,
        textTransform: 'none',
      },
      maxLines: 2,
      marginTop: 0,
      marginBottom: 0,
      opacity: 0.75,
    },
    body: {
      id: 'body',
      role: 'body',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 25, story: 27, landscape: 23 },
        fontWeight: 400,
        lineHeight: 1.55,
        letterSpacing: 0,
        textTransform: 'none',
      },
      maxLines: 5,
      marginTop: 0,
      marginBottom: 0,
      opacity: 0.85,
    },
    footer: {
      id: 'footer',
      role: 'footer',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 16, story: 18, landscape: 16 },
        fontWeight: 600,
        lineHeight: 1.4,
        letterSpacing: 2.5,
        textTransform: 'uppercase',
      },
      maxLines: 1,
      marginTop: 36,
      marginBottom: 0,
      opacity: 0.6,
    },
  },
  accentLine: {
    enabled: true,
    position: 'below-headline',
    thickness: 3,
    widthPercent: 10,
    color: '#D9B98A',
    opacity: 0.9,
  },
};
