import type { TemplateConfig } from './types';

export const heroTemplate: TemplateConfig = {
  id: 'hero',
  name: 'Hero Title',
  description: 'Bold, oversized headline with generous whitespace. Perfect for impactful statements.',
  safeArea: {
    square: { top: 120, right: 80, bottom: 110, left: 80 },
    story: { top: 280, right: 72, bottom: 200, left: 72 },
    landscape: { top: 100, right: 120, bottom: 90, left: 120 },
  },
  layout: {
    square: { justifyContent: 'flex-end', gap: 24 },
    story: { justifyContent: 'flex-end', gap: 32 },
    landscape: { justifyContent: 'flex-end', gap: 20 },
  },
  zones: {
    kicker: {
      id: 'kicker',
      role: 'kicker',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 26, story: 28, landscape: 24 },
        fontWeight: 600,
        lineHeight: 1.3,
        letterSpacing: 3,
        textTransform: 'uppercase',
      },
      maxLines: 1,
      marginTop: 0,
      marginBottom: 6,
      opacity: 1,
    },
    headline: {
      id: 'headline',
      role: 'headline',
      typography: {
        fontFamily: 'headline',
        fontSize: { square: 96, story: 104, landscape: 84 },
        fontWeight: 700,
        lineHeight: 1.02,
        letterSpacing: -2.5,
        textTransform: 'none',
      },
      maxLines: 5,
      marginTop: 0,
      marginBottom: 0,
      opacity: 1,
    },
    subtitle: {
      id: 'subtitle',
      role: 'subtitle',
      typography: {
        fontFamily: 'headline',
        fontSize: { square: 38, story: 42, landscape: 36 },
        fontWeight: 500,
        lineHeight: 1.2,
        letterSpacing: -0.5,
        textTransform: 'none',
      },
      maxLines: 2,
      marginTop: 6,
      marginBottom: 0,
      opacity: 0.78,
    },
    body: {
      id: 'body',
      role: 'body',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 27, story: 29, landscape: 25 },
        fontWeight: 400,
        lineHeight: 1.5,
        letterSpacing: 0,
        textTransform: 'none',
      },
      maxLines: 4,
      marginTop: 8,
      marginBottom: 0,
      opacity: 0.88,
    },
    footer: {
      id: 'footer',
      role: 'footer',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 18, story: 20, landscape: 18 },
        fontWeight: 500,
        lineHeight: 1.4,
        letterSpacing: 1.5,
        textTransform: 'uppercase',
      },
      maxLines: 1,
      marginTop: 28,
      marginBottom: 0,
      opacity: 0.65,
    },
  },
  accentLine: {
    enabled: true,
    position: 'below-headline',
    thickness: 3,
    widthPercent: 12,
    color: '#D9B98A',
    opacity: 0.9,
  },
};
