import type { TemplateConfig } from './types';

export const imageLedTemplate: TemplateConfig = {
  id: 'image-led',
  name: 'Image-led',
  description: 'Designed for image backgrounds. Compact text at bottom with strong overlay support.',
  safeArea: {
    square: { top: 80, right: 80, bottom: 90, left: 80 },
    story: { top: 160, right: 72, bottom: 150, left: 72 },
    landscape: { top: 72, right: 110, bottom: 80, left: 110 },
  },
  layout: {
    square: { justifyContent: 'flex-end', gap: 16 },
    story: { justifyContent: 'flex-end', gap: 20 },
    landscape: { justifyContent: 'flex-end', gap: 14 },
  },
  zones: {
    kicker: {
      id: 'kicker',
      role: 'kicker',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 26, story: 28, landscape: 24 },
        fontWeight: 700,
        lineHeight: 1.3,
        letterSpacing: 2.5,
        textTransform: 'uppercase',
      },
      maxLines: 1,
      marginTop: 0,
      marginBottom: 6,
      opacity: 1,
    },
    headline: {
      id: 'headline',
      role: 'headline',
      typography: {
        fontFamily: 'headline',
        fontSize: { square: 72, story: 80, landscape: 62 },
        fontWeight: 700,
        lineHeight: 1.04,
        letterSpacing: -1.5,
        textTransform: 'none',
      },
      maxLines: 4,
      marginTop: 0,
      marginBottom: 0,
      opacity: 1,
    },
    subtitle: {
      id: 'subtitle',
      role: 'subtitle',
      typography: {
        fontFamily: 'headline',
        fontSize: { square: 34, story: 38, landscape: 30 },
        fontWeight: 500,
        lineHeight: 1.2,
        letterSpacing: -0.3,
        textTransform: 'none',
      },
      maxLines: 2,
      marginTop: 4,
      marginBottom: 0,
      opacity: 0.8,
    },
    body: {
      id: 'body',
      role: 'body',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 25, story: 27, landscape: 23 },
        fontWeight: 400,
        lineHeight: 1.5,
        letterSpacing: 0.2,
        textTransform: 'none',
      },
      maxLines: 3,
      marginTop: 6,
      marginBottom: 0,
      opacity: 0.9,
    },
    footer: {
      id: 'footer',
      role: 'footer',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 16, story: 18, landscape: 16 },
        fontWeight: 600,
        lineHeight: 1.4,
        letterSpacing: 2.5,
        textTransform: 'uppercase',
      },
      maxLines: 1,
      marginTop: 24,
      marginBottom: 0,
      opacity: 0.65,
    },
  },
  accentLine: {
    enabled: true,
    position: 'below-headline',
    thickness: 3,
    widthPercent: 10,
    color: '#D9B98A',
    opacity: 0.85,
  },
};
