import type { TemplateConfig } from './types';

export const quoteTemplate: TemplateConfig = {
  id: 'quote',
  name: 'Quote',
  description: 'Elegant typography for quotes and testimonials. Italic headline with attribution.',
  safeArea: {
    square: { top: 140, right: 100, bottom: 130, left: 100 },
    story: { top: 360, right: 80, bottom: 260, left: 80 },
    landscape: { top: 120, right: 200, bottom: 110, left: 200 },
  },
  layout: {
    square: { justifyContent: 'center', gap: 16 },
    story: { justifyContent: 'center', gap: 24 },
    landscape: { justifyContent: 'center', gap: 14 },
  },
  zones: {
    kicker: {
      id: 'kicker',
      role: 'kicker',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 22, story: 24, landscape: 20 },
        fontWeight: 600,
        lineHeight: 1.3,
        letterSpacing: 3,
        textTransform: 'uppercase',
      },
      maxLines: 1,
      marginTop: 0,
      marginBottom: 12,
      opacity: 1,
    },
    headline: {
      id: 'headline',
      role: 'headline',
      typography: {
        fontFamily: 'headline',
        fontSize: { square: 58, story: 62, landscape: 52 },
        fontWeight: 500,
        lineHeight: 1.22,
        letterSpacing: -0.5,
        textTransform: 'none',
      },
      maxLines: 6,
      marginTop: 0,
      marginBottom: 0,
      opacity: 1,
    },
    subtitle: {
      id: 'subtitle',
      role: 'subtitle',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 27, story: 29, landscape: 25 },
        fontWeight: 500,
        lineHeight: 1.3,
        letterSpacing: 0,
        textTransform: 'none',
      },
      maxLines: 2,
      marginTop: 8,
      marginBottom: 0,
      opacity: 0.68,
    },
    body: {
      id: 'body',
      role: 'body',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 23, story: 25, landscape: 21 },
        fontWeight: 400,
        lineHeight: 1.5,
        letterSpacing: 0,
        textTransform: 'none',
      },
      maxLines: 3,
      marginTop: 16,
      marginBottom: 0,
      opacity: 0.72,
    },
    footer: {
      id: 'footer',
      role: 'footer',
      typography: {
        fontFamily: 'body',
        fontSize: { square: 18, story: 20, landscape: 17 },
        fontWeight: 500,
        lineHeight: 1.4,
        letterSpacing: 0.5,
        textTransform: 'none',
      },
      maxLines: 1,
      marginTop: 44,
      marginBottom: 0,
      opacity: 0.6,
    },
  },
  accentLine: {
    enabled: true,
    position: 'above-footer',
    thickness: 2,
    widthPercent: 8,
    color: '#D9B98A',
    opacity: 0.85,
  },
};
